name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create dummy env files
        run: |
          mkdir -p env
          echo 'appSetup=Dev' > env/.env.dev
          echo 'baseURL=${{ secrets.BACKEND_URL }}' >> env/.env.dev
          echo 'appSetup=Test' > env/.env.test
          echo 'baseURL=${{ secrets.BACKEND_URL }}' >> env/.env.test
          echo 'appSetup=Prod' > env/.env.prod
          echo 'baseURL=${{ secrets.BACKEND_URL }}' >> env/.env.prod

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: |
          flutter build web --release --base-href "/ams_flutter/"
          touch build/web/.nojekyll

      - name: Remove gitignore before deploy
        run: rm -f .gitignore

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
